config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :users#, only: [:new, :create, :show, :edit]
  resources :favorites, only: [:create, :destroy]
  resources :blogs do
    collection do
      post :confirm
      patch :confirm
    end
    member do
      patch :confirm
    end
  end
  get "users/:id/favorites" => "users#favorites"
  get "/" => "blogs#index"
  # mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  # post "users/:id/update" => "users#update"
  # get "users/:id/edit" => "users#edit"
  # post "users/:id/edit" => "users#edit"
  # patch "users/:id" => "users#update"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    validates :content, presence: true
    validates :image, presence: true
    belongs_to :user
    has_many :favorites, dependent: :destroy
    has_many :favorite_users, through: :favorites, source: :user
    mount_uploader :image, ImageUploader
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
  # validates :firstname,  presence: true, length: { maximum: 30 }
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :blogs
  has_many :favorites, dependent: :destroy
  has_many :favorite_blogs, through: :favorites, source: :blog
  mount_uploader :profile_image, ImageUploader
  # mount_uploader :cover_image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def edit
  end

  def create
    @blog = current_user.blogs.build(blog_params)
    if @blog.save
      # ContactMailer.contact_mail(@blog).deliver
      redirect_to blogs_path, notice: "作成しました！"
    else
      # 入力フォームを再描画します。
      render :new
    end
  end

  def update
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: "編集しました！"
    else
      render :edit
    end
  end

  def show
    @favorite = current_user.favorites.find_by(blog_id: @blog.id)
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path, notice:"ブログを削除しました！"
  end

  def confirm
    @blog = current_user.blogs.build(blog_params)
    render :new if @blog.invalid?
  end
  private
  def blog_params
    params.require(:blog).permit(:content, :image, :image_cache)
  end
  def set_blog
    @blog = Blog.find(params[:id])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    favorite = current_user.favorites.create(blog_id: params[:blog_id])
    redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました'
      render :new
    end
  end
  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_user, only: [:edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "プロフィールを編集しました！"
    else
      render :edit
    end
  end

  def favorites
    @user = User.find_by(id: params[:id])
    @favorites = current_user.favorite_blogs.all
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :profile_text,
                                 :password_confirmation, :profile_image)
  end

  def check_user
    @user = User.find(params[:id])
    unless current_user.id == @user.id
      flash[:notice] = "編集権限がありません"
      redirect_to blogs_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm' || action_name == 'create'
      confirm_blogs_path
    elsif action_name == 'edit'
      confirm_blog_path
    end
  end

  def confirm_new_or_edit
    # ブログ新規投稿とアップデートに分岐したいが…
    unless @blog.id?
      blogs_path
    else
      blog_path
    end
  end

  def confirm_form_method
    @blog.id ? 'patch' : 'post'
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true, url: choose_new_or_edit) do |form| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="blog_title">
    <%= form.label :content %>
    <%= form.text_area :content, :size=>"100x5" %>
  </div>
  <div class="blog_title">
    <%= form.label :"画像" %>
    <%= form.file_field :image %>
  </div>
  <br><br>
  <%= form.submit "更新する" %>
<% end %>

<%= link_to "みんなの投稿一覧にもどる", blogs_path %><br>
<%= link_to "マイページに戻る", user_path(current_user.id) %>

app/views/blogs/confirm.html.erb
<h3>以下の内容で、送信しますか。公開される写真は、画面に収まる適切なサイズで表示されます。</h3>

<%= form_with(model: @blog, url: confirm_new_or_edit, method: confirm_form_method, local: true) do |form| %>
  <%= form.hidden_field :content %>
  <%= image_tag(@blog.image.url) if @blog.image && @blog.image.url %>
  <%= form.hidden_field :image_cache %>
  <p>本文：<%= @blog.content %></p>
  <%= form.submit "登録する" %>
  <%= form.submit "戻る", name: 'back' %>
<% end %>

app/views/blogs/edit.html.erb
<h2>投稿を編集する</h2>
<%= render 'form' %>

app/views/blogs/index.html.erb
<h1>みんなの写真一覧</h1>
<p>ログインすると、コメント付きの詳細ページへアクセスでき、お気に入り登録ができます。</p>
<p><%= notice %></p>
<% @blogs.each do |blog| %>
■<%= link_to(blog.user.name, "/users/#{blog.user.id}") %><br>
<%= blog.created_at %><br>
<p>
<%= image_tag blog.image.url ,class: "blog_image" if blog.image? %>
</p>
<br>

<% if logged_in? %>
<%= link_to '詳細を確認する', blog_path(blog.id) %><br>
<% end %>
<hr width="800" noshade>
<% end %>
<% if logged_in? %>
  <%= link_to '新しくブログを投稿する', new_blog_path %>
<% end %>

app/views/blogs/new.html.erb
<h2>その気持ち、シェアしよう</h2>
<%= render 'form' %>

app/views/blogs/show.html.erb
<h1>投稿詳細画面</h1>
<p>内容: <%= @blog.content %></p>
<p>投稿者名: <%= @blog.user.name %></p>
<p>日時: <%= @blog.created_at %></p>
<p>
  <%= image_tag @blog.image.url ,class: "blog_image" %>
  <%# <%= image_tag @blog.image.url if @blog.image?,class: "blog_image" %>
</p>
<% if @blog.user_id == current_user.id %>
  <div>
    <td><%= link_to "編集する", "/blogs/#{@blog.id}/edit" %></td>
    <td><%= link_to '削除する', blog_path, method: :delete ,data: { confirm: '本当に削除していいですか？' } %></td>
  </div>
<% end %>
<% unless @blog.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(blog_id: @blog.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>

app/views/favorites/index.htmk.erb
<h2>Favorites list</h2>
<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>Picture</th>
  </tr>
  <tr>
    <% @favorites.each do |favorite| %>
    <td><%= favorite.title %></td>
    <td><%= favorite.content %></td>
    <td><%= image_tag favorite.picture.url %></td>
  </tr>
<% end %>
</table>

app/views/layouts/application.html.erb
<html>
  <head>
    <title>INSTASITE</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <div class="container">
    <header>
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>
      <% if logged_in? %>
        <%= link_to "INSTASITE", blogs_path %>　　
        <%= link_to "みんなの写真一覧", blogs_path %>　　　
        <%= link_to "マイページ", user_path(current_user.id) %>　　　
        <%= link_to "ログアウト", session_path(current_user.id), method: :delete %>
      <% else %>
        <%= link_to "INSTASITE", new_user_path %>　　
        <%= link_to "みんなの写真一覧", blogs_path %>　　
        <%= link_to "Sign up", new_user_path %>　　　
        <%= link_to "ログイン", new_session_path %>
      <% end %>
      <%= yield %>
   </header>
   <footer class="footer">
     <p> © INSTASITE Corp. All RIGHTS RESERVED.</p>
   </footer>
 </div>
</html>

app/views/users/edit.html.erb
<h1>FACEPAGE　マイプロフィール編集</h1>
<p>パスワード変更がない場合も、再入力をお願いします。</p>
■プロフィール画像
<%= image_tag @user.profile_image.url if @user.profile_image? %>
<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :"名前" %>
  <%= f.text_field :name %><br>
  <%= f.label :"自己紹介" %>
  <%= f.text_area :profile_text, :size=>"50x2" %><br>
  <%= f.label :email %>
  <%= f.email_field :email %><br>
  <%= f.label :password %>
  <%= f.password_field :password %><br>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %><br>
  <%= f.label :"プロフィール画像を変更する" %>
  <%= f.file_field :profile_image %><br>
  <%= f.submit "更新する" %>
<% end %>

<%= link_to "みんなの投稿に戻る", user_path(current_user.id) %><br>
<%= link_to "マイページに戻る", user_path(current_user.id) %>

app/views/users/favorites.html.erb
<h1>いいね！した投稿一覧</h1>
<% @favorites.each do |favorite| %>
<%= link_to(favorite.user.name, "/users/#{favorite.user.id}") %><br>
<%= favorite.created_at %><br>
<%= favorite.content %><br>
<%= image_tag favorite.image.url ,class: "blog_image" %><br>
<hr width="800" noshade>
<% end %>

app/views/users/new.html.erb
<h1>FACEPAGE ユーザー登録</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :"名前" %>
  <%= f.text_field :name %><br>
  <%= f.label :"自己紹介" %>
  <%= f.text_field :profile_text %><br>
  <%= f.label :email %>
  <%= f.email_field :email %><br>
  <%= f.label :password %>
  <%= f.password_field :password %><br>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %><br>
  <div>
    <%= f.label :"プロフィール画像" %>
    <%= f.file_field :profile_image %>
  </div>
  <!-- <div>
    <%= f.label :"カバー画像" %>
    <%= f.file_field :cover_image %>
  </div> -->
  <%= f.submit "アカウントを登録する" %>
<% end %>

アカウントをお持ちの方は<%= link_to "こちらのログインページへ", new_session_path %>

app/views/users/show.html.erb
<div class="show clearfix">
  <h1><%= @user.name %>のマイページ</h1>
  ■自己紹介<br>
  <%= @user.profile_text%><br><br>
  <% if @user == current_user %>
  <%= link_to '写真をシェアしよう', new_blog_path %>　　
  <%= link_to 'プロフィール・自己紹介文編集', edit_user_path %>　　
  <%= link_to 'お気に入り一覧', "/users/#{@user.id}/favorites" %><br>
  <% end %>
  <%= image_tag @user.profile_image.url ,class: "user_image" %>
</div>
<br>

  <article class="contett">
    <div>
      <% @user.blogs.each do |blog| %>
      <div>
        <p><%= blog.user.name %></p>
        <p><%= blog.created_at %></p>
        <p><%= image_tag blog.image.url ,class: "blog_image" if blog.image? %> </p>
        <p><%= blog.content %></p><br>
        <% if logged_in? %>
        <%= link_to '詳細を確認する', blog_path(blog.id) %><br>
        <% end %>
        <hr width="800" noshade>
      </div>
      <% end %>
    </div>
  </article>